apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-detector-ai
spec:
  selector:
    matchLabels:
      app: car-detector-ai
  template:
    metadata:
      labels:
        app: car-detector-ai
    spec:
      containers:
        - name: car-detector-ai
          image: akos0628/car-detector-ai:{{ .Values.env.APP_VERSION }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
